### ISSUE TITLE
Cockpit Next - API CORS bug

### ISSUE THREAD

**Issue by joejordanbrown** [COCOPi/cockpit#431]
Filter part of the API wont work from other domains due to not being allowed to set the header “application/json” error “Content-Type is not allowed by Access-Control-Allow-Headers” when calling 

Temporary workaround in the .htaccess file:
Header set Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept"

**Comment by aheinze** [comment]
Thanks, should be fixed now

**Comment by peterbrinck** [comment]
Hi!

I still have problems with this..
When using Postman, I can get a response from the API with a status code of 200

But when I'm trying with something like [`request`](https://github.com/request/request) in my React app, I get this error:
`No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

If I call another API, it works just fine.
Also, when I send my request, I add the header: `Content-Type: application/json`
